# Generated by Django 5.2.17 on 2026-10-05 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='ditugaskan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan ke'),
        ),
        migrations.AddField(
            model_name='followup',
            name='diubah_pada',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Diubah pada'),
        ),
        migrations.AddField(
            model_name='followup',
            name='prioritas',
            field=models.CharField(blank=True, default='NORMAL', max_length=12, verbose_name='Prioritas'),
        ),
        migrations.AddField(
            model_name='followup',
            name='selesai_pada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Selesai pada'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Harga SPP'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='harga_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Harga SPP (ubah)'),
        ),
    ]
