# Generated by Django 5.2.17 on 2026-10-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_catatan_murid'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmaster',
            name='kontak_darurat',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Kontak darurat (nama)'),
        ),
        migrations.AddField(
            model_name='parentmaster',
            name='telp_darurat',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telepon darurat'),
        ),
    ]
