# Generated by Django 5.2.17 on 2026-10-05 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, max_length=60, verbose_name='Sesi ID')),
                ('std', models.CharField(db_index=True, max_length=40, verbose_name='Student ID')),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('TERLAMBAT', 'Terlambat'), ('IZIN', 'Izin'), ('ABSEN', 'Tidak hadir')], max_length=12, verbose_name='Status')),
                ('catatan', models.CharField(blank=True, default='', max_length=300, verbose_name='Catatan')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.branch')),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sid', 'std'],
                'indexes': [models.Index(fields=['branch', 'std'], name='classes_keh_branch__79ac84_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'sid', 'std'), name='uq_kehadiran_sesi_murid')],
            },
        ),
    ]
