# Generated by Django 5.2.17 on 2026-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bukukas_dihitung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buktibayar',
            name='nominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Nominal'),
        ),
        migrations.AlterField(
            model_name='spptagihan',
            name='adj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Penyesuaian'),
        ),
        migrations.AlterField(
            model_name='spptagihan',
            name='diskon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='spptagihan',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Harga SPP'),
        ),
    ]
