# Generated by Django 5.2.17 on 2026-10-01 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='mis. SPI-AS', max_length=20, unique=True, verbose_name='Branch ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama cabang')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Kota')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('status', models.CharField(choices=[('NEW_BRANCH', 'NEW_BRANCH (belum beroperasi)'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='NEW_BRANCH', max_length=12, verbose_name='Status cabang')),
                ('language', models.CharField(default='Indonesia', max_length=40, verbose_name='Bahasa utama')),
                ('currency', models.CharField(default='IDR', max_length=8, verbose_name='Mata uang')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Tanggal buka cabang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cabang',
                'verbose_name_plural': 'Cabang',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='Kunci')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Parameter')),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('row_no', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='branches.branch')),
            ],
            options={
                'ordering': ['row_no', 'key'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'key'), name='uq_branch_setting_key')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BRANCH_ADMIN', 'Branch Admin'), ('MANAGER', 'Manager'), ('CSO', 'CSO'), ('FINANCE', 'Finance'), ('ACADEMIC', 'Academic'), ('TEACHER', 'Teacher')], max_length=20, verbose_name='Peran')),
                ('teacher_name', models.CharField(blank=True, max_length=100, verbose_name='Nama guru (seperti di jadwal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='uq_membership_user_branch')],
            },
        ),
    ]
