# Generated by Django 5.2.17 on 2026-10-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Baris')),
                ('batch', models.CharField(db_index=True, max_length=200, verbose_name='Import Batch')),
                ('date', models.TextField(blank=True, default='', verbose_name='Import Date')),
                ('file', models.TextField(blank=True, default='', verbose_name='Source File')),
                ('path', models.TextField(blank=True, default='', verbose_name='Source Path')),
                ('sha', models.TextField(blank=True, default='', verbose_name='SHA-256')),
                ('sheets', models.TextField(blank=True, default='', verbose_name='Source Sheets')),
                ('rows', models.TextField(blank=True, default='', verbose_name='Rows Imported')),
                ('excluded', models.TextField(blank=True, default='', verbose_name='Rows Excluded')),
                ('ver', models.TextField(blank=True, default='', verbose_name='Script Version')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
            ],
            options={
                'verbose_name': 'IMPORT_LOG',
                'verbose_name_plural': 'IMPORT_LOG',
                'db_table': 'x_import_log',
                'ordering': ['row_no', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Baris')),
                ('lid', models.CharField(db_index=True, max_length=200, verbose_name='Log ID')),
                ('user', models.TextField(blank=True, default='', verbose_name='User')),
                ('action', models.TextField(blank=True, default='', verbose_name='Action')),
                ('entity', models.TextField(blank=True, default='', verbose_name='Entity')),
                ('eid', models.TextField(blank=True, default='', verbose_name='Entity ID')),
                ('field', models.TextField(blank=True, default='', verbose_name='Field')),
                ('old', models.TextField(blank=True, default='', verbose_name='Old Value')),
                ('new', models.TextField(blank=True, default='', verbose_name='New Value')),
                ('ts', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('by', models.TextField(blank=True, default='', verbose_name='Detected By')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
            ],
            options={
                'verbose_name': 'AUDIT_LOG',
                'verbose_name_plural': 'AUDIT_LOG',
                'db_table': 'x_audit_log',
                'ordering': ['row_no', 'pk'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('branch', 'lid'), name='uq_audit_log_key')],
            },
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Baris')),
                ('sid', models.CharField(db_index=True, max_length=200, verbose_name='Source ID')),
                ('file', models.TextField(blank=True, default='', verbose_name='Source File')),
                ('sheet', models.TextField(blank=True, default='', verbose_name='Source Sheet')),
                ('role', models.TextField(blank=True, default='', verbose_name='Peran')),
                ('period', models.TextField(blank=True, db_index=True, default='', verbose_name='Periode')),
                ('used', models.TextField(blank=True, default='', verbose_name='Dipakai di')),
                ('rows', models.TextField(blank=True, default='', verbose_name='Baris')),
                ('excluded', models.TextField(blank=True, default='', verbose_name='Dikecualikan')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
            ],
            options={
                'verbose_name': 'SOURCE_REFERENCE',
                'verbose_name_plural': 'SOURCE_REFERENCE',
                'db_table': 'x_source_reference',
                'ordering': ['row_no', 'pk'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('branch', 'sid'), name='uq_source_reference_key')],
            },
        ),
    ]
