# Generated by Django 5.2.17 on 2026-10-05 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('action', models.CharField(choices=[('LOGIN', 'Masuk'), ('LOGOUT', 'Keluar'), ('LOGIN_GAGAL', 'Gagal masuk')], max_length=20, verbose_name='Aksi')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat keamanan',
                'verbose_name_plural': 'Riwayat keamanan',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
