# Generated by Django 5.2.17 on 2026-10-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Baris')),
                ('iid', models.CharField(db_index=True, max_length=200, verbose_name='Issue ID')),
                ('unit', models.TextField(blank=True, default='', verbose_name='Unit')),
                ('type', models.TextField(blank=True, default='', verbose_name='Issue Type')),
                ('std', models.TextField(blank=True, db_index=True, default='', verbose_name='Student ID')),
                ('nama', models.TextField(blank=True, default='', verbose_name='Nama Murid')),
                ('code', models.TextField(blank=True, db_index=True, default='', verbose_name='Kode Kelas')),
                ('month', models.DateField(blank=True, null=True, verbose_name='Month')),
                ('source', models.TextField(blank=True, default='', verbose_name='Source')),
                ('desc', models.TextField(blank=True, default='', verbose_name='Issue Description')),
                ('expected', models.TextField(blank=True, default='', verbose_name='Expected Value')),
                ('actual', models.TextField(blank=True, default='', verbose_name='Actual Value')),
                ('sev', models.TextField(blank=True, default='', verbose_name='Severity')),
                ('status', models.TextField(blank=True, default='', verbose_name='Status')),
                ('assigned', models.TextField(blank=True, default='', verbose_name='Assigned To')),
                ('reviewer', models.TextField(blank=True, default='', verbose_name='Reviewer')),
                ('created', models.DateField(blank=True, null=True, verbose_name='Created Date')),
                ('resolved', models.DateField(blank=True, null=True, verbose_name='Resolved Date')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='Resolution')),
                ('evidence', models.TextField(blank=True, default='', verbose_name='Evidence')),
                ('still', models.TextField(blank=True, default='', verbose_name='Kondisi Masih Ada')),
                ('kat', models.TextField(blank=True, default='', verbose_name='Kategori')),
                ('s360', models.FloatField(blank=True, null=True, verbose_name='S360')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
            ],
            options={
                'verbose_name': 'ISSUE_UNIT',
                'verbose_name_plural': 'ISSUE_UNIT',
                'db_table': 'x_issue_unit',
                'ordering': ['row_no', 'pk'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('branch', 'iid'), name='uq_issue_unit_key')],
            },
        ),
    ]
