# Generated by Django 5.2.17 on 2026-10-06 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(db_index=True, max_length=40, verbose_name='Student ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama murid (saat diajukan)')),
                ('level', models.CharField(max_length=80, verbose_name='Level')),
                ('kode_level', models.CharField(blank=True, default='', max_length=10, verbose_name='Kode level')),
                ('kode_kelas', models.CharField(blank=True, default='', max_length=60, verbose_name='Kode kelas')),
                ('guru', models.CharField(blank=True, default='', max_length=120, verbose_name='Guru')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul project')),
                ('deskripsi', models.TextField(blank=True, default='', verbose_name='Deskripsi project')),
                ('link', models.URLField(blank=True, default='', max_length=500, verbose_name='Link project')),
                ('tgl_selesai', models.DateField(verbose_name='Tanggal presentasi / selesai')),
                ('nilai_konsep', models.PositiveSmallIntegerField(verbose_name='Pemahaman konsep')),
                ('nilai_logika', models.PositiveSmallIntegerField(verbose_name='Logika & problem solving')),
                ('nilai_kreativitas', models.PositiveSmallIntegerField(verbose_name='Kreativitas & kualitas project')),
                ('nilai_presentasi', models.PositiveSmallIntegerField(verbose_name='Presentasi & komunikasi')),
                ('kekuatan', models.TextField(blank=True, default='', verbose_name='Kekuatan murid')),
                ('perlu_ditingkatkan', models.TextField(blank=True, default='', verbose_name='Yang perlu ditingkatkan')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan guru untuk orang tua')),
                ('rekomendasi', models.CharField(blank=True, default='', max_length=80, verbose_name='Rekomendasi level berikutnya')),
                ('status', models.CharField(choices=[('DIAJUKAN', 'Menunggu persetujuan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], db_index=True, default='DIAJUKAN', max_length=10, verbose_name='Status')),
                ('diajukan_pada', models.DateTimeField(auto_now_add=True)),
                ('diputuskan_pada', models.DateTimeField(blank=True, null=True)),
                ('alasan_tolak', models.TextField(blank=True, default='', verbose_name='Alasan ditolak')),
                ('cert_no', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Nomor sertifikat')),
                ('cert_tgl', models.DateField(blank=True, null=True, verbose_name='Tanggal sertifikat')),
                ('cert_png', models.CharField(blank=True, default='', max_length=300)),
                ('cert_pdf', models.CharField(blank=True, default='', max_length=300)),
                ('cert_preview', models.CharField(blank=True, default='', max_length=300)),
                ('aid', models.CharField(blank=True, default='', max_length=40, verbose_name='Record ID akademik')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.branch')),
                ('diajukan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diputuskan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Final project',
                'ordering': ['-diajukan_pada'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cert_no', ''), _negated=True), fields=('branch', 'cert_no'), name='uq_final_project_cert_no')],
            },
        ),
    ]
